/* Auto-generated by scripts/preprocess_facilities.py */
/* Source: regional_incinerator_candidates_combined.csv + 경기도_폐기물처리업체현황.csv (경기 좌표) + Kakao geocoding (인천/충남) */

/* 39개 민간 소각장 후보 (실데이터 기반, 단가·잔여용량·CO₂는 추정) */
const PRIVATE_FACILITIES = [
  {
    "name": "경기 리뉴에너지경기",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 170000,
    "co2": 0.52,
    "lat": 37.354049,
    "lng": 127.364479,
    "address": "경기도 광주시 곤지암읍 열미길 22",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 청송산업개발",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 170000,
    "co2": 0.51,
    "lat": 37.9071,
    "lng": 127.025073,
    "address": "경기도 동두천시 삼육사로652번길 60(상패동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 코어엔텍 주식회사",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.44,
    "lat": 37.345657,
    "lng": 126.704617,
    "address": "경기도 시흥시 소망공원로 5",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 시흥도시공사",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 168000,
    "co2": 0.46,
    "lat": 37.33032,
    "lng": 126.699835,
    "address": "경기도 시흥시 옥구천서로 9번길 45",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 비노텍",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.44,
    "lat": 37.296494,
    "lng": 126.790759,
    "address": "경기도 안산시 단원구 해안로 308(원시동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 대일개발",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.45,
    "lat": 37.305837,
    "lng": 126.746246,
    "address": "경기도 안산시 단원구 지원로 7(성곡동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 성림유화",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.45,
    "lat": 37.308266,
    "lng": 126.746967,
    "address": "경기도 안산시 단원구 첨단로 215(성곡동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 부경산업",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.44,
    "lat": 37.316581,
    "lng": 126.751951,
    "address": "경기도 안산시 단원구 신원로91번길 16(성곡동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 한국환경개발",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.45,
    "lat": 37.306835,
    "lng": 126.744521,
    "address": "경기도 안산시 단원구 첨단로207번길 5(성곡동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 가나에너지",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 167000,
    "co2": 0.45,
    "lat": 37.863845,
    "lng": 126.985912,
    "address": "경기도 양주시 남면 삼일로485번길 92",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 애니테크",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 168000,
    "co2": 0.47,
    "lat": 37.876744,
    "lng": 127.00737,
    "address": "경기도 양주시 남면 운하로 66-14",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 이도에코오산",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 173000,
    "co2": 0.6,
    "lat": 37.141779,
    "lng": 127.055505,
    "address": "경기도 오산시 황새로 149번길 55(누읍동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 뉴그린",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 182000,
    "co2": 0.84,
    "lat": 36.986748,
    "lng": 126.833278,
    "address": "경기도 평택시 포승읍 원정리 1204-4",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 화성그린에너지밸류",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 176000,
    "co2": 0.68,
    "lat": 37.085936,
    "lng": 126.903497,
    "address": "경기도 화성시 향남읍 발안공단로 139",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 신대한정유산업",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 172000,
    "co2": 0.57,
    "lat": 37.161057,
    "lng": 127.01559,
    "address": "경기도 화성시 정남면 가장로 334-10",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "경기 신승에너지",
    "region": "경기",
    "flag": "g",
    "cap": null,
    "remain": null,
    "unitCost": 174000,
    "co2": 0.61,
    "lat": 37.155289,
    "lng": 126.804097,
    "address": "경기도 화성시 매바위로 570-10(장덕동)",
    "wasteType": null,
    "geoSource": "gyeonggi_csv"
  },
  {
    "name": "충남 환경에너지사업소",
    "region": "충남",
    "flag": "r",
    "cap": 320.0,
    "remain": 80.0,
    "unitCost": 229000,
    "co2": 1.07,
    "lat": 36.819749,
    "lng": 127.115111,
    "address": "충청남도 천안시 서북구 백석동 531",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 환경에너지사업소",
    "region": "충남",
    "flag": "r",
    "cap": 250.0,
    "remain": 62.5,
    "unitCost": 229000,
    "co2": 1.07,
    "lat": 36.819749,
    "lng": 127.115111,
    "address": "충청남도 천안시 서북구 백석동 531",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 환경과학공원",
    "region": "충남",
    "flag": "r",
    "cap": 200.0,
    "remain": 50.0,
    "unitCost": 230000,
    "co2": 1.09,
    "lat": 36.799925,
    "lng": 126.977208,
    "address": "충청남도 아산시 배미로 154",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 공주시청",
    "region": "충남",
    "flag": "r",
    "cap": 50.0,
    "remain": 12.5,
    "unitCost": 255000,
    "co2": 1.63,
    "lat": 36.425057,
    "lng": 127.06306,
    "address": "충청남도 공주시 검상동 326",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 생활폐기물종합처리장",
    "region": "충남",
    "flag": "r",
    "cap": 50.0,
    "remain": 12.5,
    "unitCost": 265000,
    "co2": 1.83,
    "lat": 36.338246,
    "lng": 126.538514,
    "address": "충청남도 보령시 남곡동 1140-6",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 환경자원화센터",
    "region": "충남",
    "flag": "r",
    "cap": 50.0,
    "remain": 12.5,
    "unitCost": 273000,
    "co2": 2.03,
    "lat": 36.157171,
    "lng": 127.132369,
    "address": "충청남도 논산시 은진면 버들길 137",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 환경관리사업소",
    "region": "충남",
    "flag": "r",
    "cap": 45.0,
    "remain": 11.2,
    "unitCost": 243000,
    "co2": 1.38,
    "lat": 36.789378,
    "lng": 126.27771,
    "address": "충청남도 태안군 태안읍 삭선리 21-3",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 맑은물누리센터",
    "region": "충남",
    "flag": "r",
    "cap": 40.0,
    "remain": 10.0,
    "unitCost": 240000,
    "co2": 1.3,
    "lat": 36.663341,
    "lng": 126.84129,
    "address": "충청남도 예산군 대흥면 대률리 산51-1",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 계룡시청",
    "region": "충남",
    "flag": "r",
    "cap": 31.2,
    "remain": 7.8,
    "unitCost": 269000,
    "co2": 1.92,
    "lat": 36.245452,
    "lng": 127.270827,
    "address": "충청남도 계룡시 두마면 입암리 516",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 생활페기물소각시설",
    "region": "충남",
    "flag": "r",
    "cap": 30.0,
    "remain": 7.5,
    "unitCost": 275000,
    "co2": 2.06,
    "lat": 36.171644,
    "lng": 127.440388,
    "address": "충청남도 금산군 추부면 용지리 432-2",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 자원순환센터",
    "region": "충남",
    "flag": "r",
    "cap": 30.0,
    "remain": 7.5,
    "unitCost": 278000,
    "co2": 2.12,
    "lat": 36.118987,
    "lng": 126.62828,
    "address": "충청남도 서천군 비인면 관리 547-1",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "충남 환경사업소",
    "region": "충남",
    "flag": "r",
    "cap": 15.0,
    "remain": 3.8,
    "unitCost": 255000,
    "co2": 1.64,
    "lat": 36.432725,
    "lng": 126.799881,
    "address": "충청남도 청양군 청양읍 벽천리 109-8",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 송도자원환경센터",
    "region": "인천",
    "flag": "y",
    "cap": 540.0,
    "remain": 135.0,
    "unitCost": 178000,
    "co2": 0.51,
    "lat": 37.353908,
    "lng": 126.61949,
    "address": "인천광역시 연수구 인천신항대로892번길 50, 송도자원환경센터",
    "wasteType": "생활",
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 청라자원환경센터",
    "region": "인천",
    "flag": "y",
    "cap": 420.0,
    "remain": 105.0,
    "unitCost": 173000,
    "co2": 0.39,
    "lat": 37.556182,
    "lng": 126.651337,
    "address": "인천광역시 서구 경서동 673-6",
    "wasteType": "생활폐기물",
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 인천국제공항공사",
    "region": "인천",
    "flag": "y",
    "cap": 140.0,
    "remain": 35.0,
    "unitCost": 183000,
    "co2": 0.63,
    "lat": 37.441073,
    "lng": 126.461797,
    "address": "인천. 중구 영종해안북로1050번길 78-13",
    "wasteType": "생활",
    "geoSource": "kakao_kw"
  },
  {
    "name": "인천 케이비아이텍",
    "region": "인천",
    "flag": "y",
    "cap": 112.0,
    "remain": 28.0,
    "unitCost": 173000,
    "co2": 0.39,
    "lat": 37.503912,
    "lng": 126.657013,
    "address": "인천광역시 서구 건지로153번길 54, 55 (석남동)",
    "wasteType": null,
    "geoSource": "kakao_kw"
  },
  {
    "name": "인천 이알지서비스",
    "region": "인천",
    "flag": "y",
    "cap": 96.0,
    "remain": 24.0,
    "unitCost": 173000,
    "co2": 0.38,
    "lat": 37.415656,
    "lng": 126.701712,
    "address": "인천광역시 남동구 남동서로316번길 41",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 경인환경에너지",
    "region": "인천",
    "flag": "y",
    "cap": 96.0,
    "remain": 24.0,
    "unitCost": 174000,
    "co2": 0.4,
    "lat": 37.556037,
    "lng": 126.638455,
    "address": "사렴로65번길 24(경서동)",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 그린스코",
    "region": "인천",
    "flag": "y",
    "cap": 80.4,
    "remain": 20.1,
    "unitCost": 174000,
    "co2": 0.4,
    "lat": 37.386793,
    "lng": 126.706286,
    "address": "앵고개로654번길 99",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 동서식품",
    "region": "인천",
    "flag": "y",
    "cap": 46.8,
    "remain": 11.7,
    "unitCost": 170000,
    "co2": 0.32,
    "lat": 37.52204,
    "lng": 126.713196,
    "address": "인천광역시 부평구 새벌로 55 (청천동)",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 에이티에너지",
    "region": "인천",
    "flag": "y",
    "cap": 44.4,
    "remain": 11.1,
    "unitCost": 173000,
    "co2": 0.39,
    "lat": 37.514074,
    "lng": 126.650295,
    "address": "중봉대로386번길 9(원창동)",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 동화기업",
    "region": "인천",
    "flag": "y",
    "cap": 43.0,
    "remain": 10.8,
    "unitCost": 173000,
    "co2": 0.38,
    "lat": 37.49584,
    "lng": 126.662503,
    "address": "염곡로 133(가좌동 173-144)",
    "wasteType": null,
    "geoSource": "kakao_addr"
  },
  {
    "name": "인천 강화군 소각장",
    "region": "인천",
    "flag": "y",
    "cap": 25.0,
    "remain": 6.2,
    "unitCost": 182000,
    "co2": 0.6,
    "lat": 37.743597,
    "lng": 126.524359,
    "address": "인천광역시 강화군 강화읍 해안북로 100",
    "wasteType": "생활",
    "geoSource": "kakao_addr"
  }
];

/* 25개 서울 자치구 좌표 (구청 위치 기준) */
const SEOUL_GU_COORDS = [
  {
    "name": "강남구",
    "lat": 37.517968,
    "lng": 127.04706
  },
  {
    "name": "강동구",
    "lat": 37.530161,
    "lng": 127.123792
  },
  {
    "name": "강북구",
    "lat": 37.639186,
    "lng": 127.02545
  },
  {
    "name": "강서구",
    "lat": 37.550966,
    "lng": 126.849532
  },
  {
    "name": "관악구",
    "lat": 37.478211,
    "lng": 126.951501
  },
  {
    "name": "광진구",
    "lat": 37.538532,
    "lng": 127.08191
  },
  {
    "name": "구로구",
    "lat": 37.495505,
    "lng": 126.888292
  },
  {
    "name": "금천구",
    "lat": 37.457066,
    "lng": 126.896037
  },
  {
    "name": "노원구",
    "lat": 37.654523,
    "lng": 127.056268
  },
  {
    "name": "도봉구",
    "lat": 37.668716,
    "lng": 127.047131
  },
  {
    "name": "동대문구",
    "lat": 37.574392,
    "lng": 127.039897
  },
  {
    "name": "동작구",
    "lat": 37.512528,
    "lng": 126.939942
  },
  {
    "name": "마포구",
    "lat": 37.566313,
    "lng": 126.901616
  },
  {
    "name": "서대문구",
    "lat": 37.579155,
    "lng": 126.936759
  },
  {
    "name": "서초구",
    "lat": 37.483625,
    "lng": 127.032683
  },
  {
    "name": "성동구",
    "lat": 37.563423,
    "lng": 127.036965
  },
  {
    "name": "성북구",
    "lat": 37.589455,
    "lng": 127.01669
  },
  {
    "name": "송파구",
    "lat": 37.514477,
    "lng": 127.10586
  },
  {
    "name": "양천구",
    "lat": 37.517075,
    "lng": 126.866543
  },
  {
    "name": "영등포구",
    "lat": 37.525963,
    "lng": 126.896367
  },
  {
    "name": "용산구",
    "lat": 37.532452,
    "lng": 126.990479
  },
  {
    "name": "은평구",
    "lat": 37.602457,
    "lng": 126.928823
  },
  {
    "name": "종로구",
    "lat": 37.574724,
    "lng": 126.979022
  },
  {
    "name": "중구",
    "lat": 37.56412,
    "lng": 126.99801
  },
  {
    "name": "중랑구",
    "lat": 37.606564,
    "lng": 127.092725
  }
];

if (typeof window !== 'undefined') {
  window.PRIVATE_FACILITIES = PRIVATE_FACILITIES;
  window.SEOUL_GU_COORDS  = SEOUL_GU_COORDS;
}
